# Generated by Django 6.0.3 on 2026-04-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria_Entregas',
            fields=[
                ('auditoria_ent_id', models.AutoField(primary_key=True, serialize=False)),
                ('entrega_id', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo_ant', models.BinaryField(blank=True, max_length='max', null=True)),
                ('archivo_nuev', models.BinaryField(blank=True, max_length='max', null=True)),
                ('comentario_ant', models.CharField(blank=True, max_length=500, null=True)),
                ('comentario_nuev', models.CharField(blank=True, max_length=500, null=True)),
                ('calificacion_ant', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calificacion_nuev', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Auditoria_Entregas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Estudiantes',
            fields=[
                ('auditoria_est_id', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante_id', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_ant', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_nuev', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos_ant', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos_nuev', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_ant', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_nuev', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_ant', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion_nuev', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_documento_ant', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_documento_nuev', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_documento_ant', models.BinaryField(blank=True, max_length='max', null=True)),
                ('numero_documento_nuev', models.BinaryField(blank=True, max_length='max', null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Auditoria_Estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Evaluaciones',
            fields=[
                ('auditoria_eva_id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion_id', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cal_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cal_nuev', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coment_ant', models.BinaryField(blank=True, max_length='max', null=True)),
                ('coment_nuev', models.BinaryField(blank=True, max_length='max', null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Auditoria_Evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Inscripciones',
            fields=[
                ('auditoria_ins_id', models.AutoField(primary_key=True, serialize=False)),
                ('inscripcion_id', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('edo_ant', models.CharField(blank=True, max_length=20, null=True)),
                ('edo_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('total_pago_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_pago_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Auditoria_Inscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Pagos',
            fields=[
                ('auditoria_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('pago_id', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_ant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_nuev', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referencia_pago_ant', models.BinaryField(blank=True, max_length='max', null=True)),
                ('referencia_pago_nuev', models.BinaryField(blank=True, max_length='max', null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Auditoria_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion_horas', models.IntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesPagos',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Detalles_Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('entrega_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.BinaryField(blank=True, max_length='max', null=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario_instructor', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Entregas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_documento', models.BinaryField(max_length='max')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.BinaryField(blank=True, max_length='max', null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('grupo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cupo_maximo', models.IntegerField()),
                ('cupo_disponible', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
            ],
            options={
                'db_table': 'Grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('inscripcion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Inscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_profesional', models.BinaryField(max_length='max')),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Instructores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('mensaje_id', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Mensajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pagos_id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('referencia_pago', models.BinaryField(max_length='max')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesUsuario',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Roles_Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_limite', models.DateField()),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.BinaryField(max_length='max')),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
